CREATE TABLE SCORELIST(
	STUNUM NUMBER,
	EXAMNUM NUMBER,
	SUBNAME VARCHAR2(30),
	EXAMDATE VARCHAR2(8),
	TEACHNAME VARCHAR2(15),
	EXAMSCORE NUMBER,
	EXAMCHK NUMBER
);

INSERT INTO SCORELIST (STUNUM, EXAMNUM, SUBNAME, EXAMDATE, TEACHNAME, EXAMSCORE) VALUES (1, 1, (SELECT SUBNAME FROM EXAMLIST WHERE EXAMNUM=1), (SELECT EXAMDATE FROM EXAMLIST WHERE EXAMNUM=1), (SELECT USERNAME FROM MEMBER WHERE USERNUM=(SELECT SUBTEACH FROM EXAMLIST WHERE EXAMNUM=1)), 80);
INSERT INTO SCORELIST (STUNUM, EXAMNUM, SUBNAME, EXAMDATE, TEACHNAME, EXAMSCORE) VALUES (1, 4, (SELECT SUBNAME FROM EXAMLIST WHERE EXAMNUM=4), (SELECT EXAMDATE FROM EXAMLIST WHERE EXAMNUM=4), (SELECT USERNAME FROM MEMBER WHERE USERNUM=(SELECT SUBTEACH FROM EXAMLIST WHERE EXAMNUM=4)), 85);
